// Modified for tython: Python type-system adaptation and independent project integration.

// Code generated by "stringer -type=ScriptKind -output=scriptkind_stringer_generated.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScriptKindUnknown-0]
	_ = x[ScriptKindJS-1]
	_ = x[ScriptKindJSX-2]
	_ = x[ScriptKindTS-3]
	_ = x[ScriptKindTSX-4]
	_ = x[ScriptKindJSON-6]
	_ = x[ScriptKindPython-8]
	_ = x[ScriptKindTypedPython-9]
}

const (
	_ScriptKind_name_0 = "ScriptKindUnknownScriptKindJSScriptKindJSXScriptKindTSScriptKindTSX"
	_ScriptKind_name_1 = "ScriptKindJSON"
	_ScriptKind_name_2 = "ScriptKindPythonScriptKindTypedPython"
)

var _ScriptKind_index_0 = [...]uint8{0, 17, 29, 42, 54, 67}
var _ScriptKind_index_2 = [...]uint8{0, 16, 37}

func (i ScriptKind) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _ScriptKind_name_0[_ScriptKind_index_0[i]:_ScriptKind_index_0[i+1]]
	case i == 6:
		return _ScriptKind_name_1
	case 8 <= i && i <= 9:
		return _ScriptKind_name_2[_ScriptKind_index_2[i-8]:_ScriptKind_index_2[i-8+1]]
	default:
		return "ScriptKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
