//go:build !noembed

// Code generated by generate.go; DO NOT EDIT.

package bundled

import "io/fs"

// embeddedContents is empty. TypeScript lib*.d.ts files are not part of Tython.
var embeddedContents = map[string]string{}

var libsEntries = []fs.DirEntry{}
