from typing import Literal, overload

@overload
def lookup(key: Literal["name"]) -> str: ...
@overload
def lookup(key: Literal["count"]) -> int: ...

class Greeting:
    name: str
    def __init__(self, name: str) -> None: ...
    def render(self, *, prefix: str = ...) -> str: ...
